$ErrorActionPreference = "Stop"

Write-Host "[qala] starting infrastructure (Postgres + Redpanda)"
docker compose -f .\infra\docker-compose.yml up -d

Write-Host "[qala] infrastructure started"
Write-Host ""
Write-Host "Start services in separate terminals:"
Write-Host "  Go:"
Write-Host "    cd .\go"
Write-Host "    go run .\cmd\user-identity-service"
Write-Host "    go run .\cmd\sde-management-service"
Write-Host "    go run .\cmd\workspace-cms-service"
Write-Host "    go run .\cmd\artifact-package-service"
Write-Host "    go run .\cmd\api-gateway"
Write-Host ""
Write-Host "  Rust:"
Write-Host "    cd .\rust"
Write-Host "    cargo run -p qala-kernel"
Write-Host "    cargo run -p ai-agents-service"
Write-Host "    cargo run -p security-sem-service"
Write-Host ""
Write-Host "  Scala:"
Write-Host "    cd .\scala"
Write-Host "    sbt workflow/run"
Write-Host "    sbt dataPlatform/run"
Write-Host "    sbt notifications/run"
